version: '2'
services:

  av-agent-utils-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: av-agent-utils-test:latest
    tty: true
    stdin_open: true
#    volumes:
#      - .:/av-agent-utils
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
